# Generated by Django 4.2.16 on 2024-12-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='image1',
            field=models.ImageField(default='', upload_to='compareimages/images/'),
        ),
    ]
