# Generated by Django 4.2.16 on 2024-12-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0003_compareimagemodels_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareimagemodels',
            name='image_title1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='compareimagemodels',
            name='image_title2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
