# Generated by Django 4.2.16 on 2024-12-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0004_alter_compareimagemodels_image_title1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='tags',
            field=models.CharField(default='', max_length=250),
        ),
    ]
