# Generated by Django 4.2.16 on 2024-12-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0005_compareimagemodels_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='categories',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='colors',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='descriptions',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_objects',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_types',
            field=models.CharField(default='', max_length=250),
        ),
    ]
