# Generated by Django 4.2.16 on 2024-12-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0006_compareimagemodels_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='image_objects',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='image_title1',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='image_title2',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='image_types',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='tags',
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='tags_similarity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
