# Generated by Django 4.2.16 on 2024-12-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0007_remove_compareimagemodels_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='categories',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='colors',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='descriptions',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image1',
            field=models.ImageField(default='', upload_to='compareimages/images/'),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image2',
            field=models.ImageField(default='', upload_to='compareimages/images/'),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_objects',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_title1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_title2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_types',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='tags',
            field=models.CharField(default='', max_length=250),
        ),
    ]
