# Generated by Django 4.2.16 on 2024-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0009_compareimagemodels_categories_similarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='compare_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
