# Generated by Django 4.2.16 on 2024-12-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0010_compareimagemodels_compare_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='Azure_used_count',
            field=models.IntegerField(default=0),
        ),
    ]
