# Generated by Django 4.2.16 on 2024-12-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0011_compareimagemodels_azure_used_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='testModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='compareimagemodels',
            name='tags',
            field=models.TextField(default='', max_length=250),
        ),
    ]
