# Generated by Django 5.1.4 on 2024-12-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0012_testmodels_alter_compareimagemodels_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='url1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='url2',
            field=models.URLField(blank=True),
        ),
    ]
