# Generated by Django 5.1.4 on 2024-12-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0013_compareimagemodels_url1_compareimagemodels_url2'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='compareimages/images/')),
            ],
        ),
    ]
