# Generated by Django 5.1.4 on 2024-12-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0014_imagemodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodels',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='imagemodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='imagemodels',
            name='image_title',
            field=models.CharField(default='', max_length=200, verbose_name='Image Title'),
        ),
        migrations.AddField(
            model_name='imagemodels',
            name='tags',
            field=models.CharField(default='', max_length=200, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='imagemodels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='imagemodels',
            name='image',
            field=models.ImageField(default='', upload_to='compareimages/images/', verbose_name='Image'),
        ),
    ]
