# Generated by Django 4.2.16 on 2024-12-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0015_alter_imagemodels_options_imagemodels_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compareimagemodels',
            old_name='compare_completed',
            new_name='completed',
        ),
    ]
