# Generated by Django 4.2.16 on 2024-12-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0016_rename_compare_completed_compareimagemodels_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='url1',
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='url2',
        ),
        migrations.AlterField(
            model_name='compareimagemodels',
            name='tags',
            field=models.CharField(default='', max_length=250),
        ),
    ]
