# Generated by Django 4.2.16 on 2024-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0018_remove_compareimagemodels_azure_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='Azure_used_count',
            field=models.IntegerField(default=0),
        ),
    ]
