# Generated by Django 4.2.16 on 2024-12-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0019_compareimagemodels_azure_used_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_key', models.CharField(default='', max_length=200)),
                ('endpoint', models.CharField(default='', max_length=200)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='testModels',
        ),
    ]
