# Generated by Django 4.2.16 on 2024-12-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0021_alter_apimodels_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodels',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
