# Generated by Django 4.2.16 on 2024-12-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0026_documentmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodels',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
