# Generated by Django 4.2.16 on 2024-12-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0028_alter_documentmodels_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='diffimage',
            field=models.ImageField(default='', upload_to='compareimages/images/'),
        ),
    ]
