# Generated by Django 4.2.16 on 2024-12-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0030_compareimagemodels_image_types_similarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compareimagemodels',
            old_name='categories',
            new_name='categories1',
        ),
        migrations.RenameField(
            model_name='compareimagemodels',
            old_name='colors',
            new_name='categories2',
        ),
        migrations.RenameField(
            model_name='compareimagemodels',
            old_name='descriptions',
            new_name='colors1',
        ),
        migrations.RenameField(
            model_name='compareimagemodels',
            old_name='image_objects',
            new_name='colors2',
        ),
        migrations.RenameField(
            model_name='compareimagemodels',
            old_name='image_types',
            new_name='descriptions1',
        ),
        migrations.RenameField(
            model_name='compareimagemodels',
            old_name='tags',
            new_name='descriptions2',
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_objects1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_objects2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_types1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='image_types2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='tags1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compareimagemodels',
            name='tags2',
            field=models.CharField(default='', max_length=250),
        ),
    ]
