# Generated by Django 4.2.16 on 2025-01-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0033_compareimagemodels_score_chi_square_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareimagemodels',
            name='score_chi_square',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='compareimagemodels',
            name='score_corr',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
    ]
