# Generated by Django 4.2.16 on 2025-01-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0035_comparefoldermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparefoldermodel',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
