# Generated by Django 4.2.16 on 2025-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0036_comparefoldermodel_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='compareNewOldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newImage', models.FileField(upload_to='newImages/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comparefoldermodel',
            name='oldImages',
        ),
        migrations.RemoveField(
            model_name='comparefoldermodel',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='comparefoldermodel',
            name='newImages',
        ),
        migrations.AddField(
            model_name='comparefoldermodel',
            name='newImages',
            field=models.ManyToManyField(to='CompareImages.comparenewoldmodel'),
        ),
    ]
