# Generated by Django 4.2.16 on 2025-01-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0037_comparenewoldmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compareFolderModel',
        ),
    ]
