# Generated by Django 4.2.16 on 2025-01-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0038_delete_comparefoldermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparenewoldmodel',
            name='oldImage',
            field=models.FileField(default='', upload_to='oldImages/'),
        ),
        migrations.AlterField(
            model_name='comparenewoldmodel',
            name='newImage',
            field=models.FileField(default='', upload_to='newImages/'),
        ),
    ]
