# Generated by Django 4.2.16 on 2025-01-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0039_comparenewoldmodel_oldimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compareNewOldModel',
        ),
    ]
