# Generated by Django 4.2.16 on 2025-01-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0040_delete_comparenewoldmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='csv',
            field=models.FileField(default='', upload_to='compareimages/csv/'),
        ),
    ]
