# Generated by Django 4.2.16 on 2025-01-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0041_compareimagemodels_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(default='', upload_to='compareimages/csv/')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='compareimagemodels',
            name='csv',
        ),
    ]
