# Generated by Django 4.2.16 on 2025-01-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompareImages', '0042_csvmodels_remove_compareimagemodels_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareimagemodels',
            name='actFlg',
            field=models.CharField(default='', max_length=250),
        ),
    ]
